alias: Hue Motion Sensor Two On Video Camara 05
initial_state: true
mode: queued
trigger:
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_two_motion
    to: 'on'
condition:
  condition: time
  after: '00:00:00'
  before: '06:00:00'
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
action:
  - service: camera.record
    data_template:
      entity_id: camera.camara_entrada
      filename: '/config/www/media/night/motion/{{ now().strftime("%Y%m%d-%H%M%S-%f") }}.mp4'
      duration: 30
      lookback: 20
