alias: Hue Motion Sensor Two On Telegram
initial_state: true
mode: queued
trigger:
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_two_motion
    to: 'on'
condition:
  condition: time
  after: '00:00:00'
  before: '06:00:00'
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
action:
  - service: notify.telegram_bacab_home_bot
    data:
      title: 'Hue Motion Sensor Two'
      message: "Camera 04"
