---
features:
  - |
    Netdata gives unparalleled insights, in real-time, of everything
    happening on your systems and applications, with stunning,
    interactive web dashboards and powerful performance and health
    alarms.
