alias: Alarm Manual Armed Away Triggered
initial_state: 'true'
trigger:
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_01_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_02_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_49fc4604_on_off
    to: 'on'
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_f2eb4604_on_off
    to: 'on'
condition:
  - condition: state
    entity_id: alarm_control_panel.alarm_manual
    state: armed_away
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm_manual
  - service: media_player.volume_set
    entity_id: media_player.amigo
    data:
      volume_level: 1.0
  - delay: '00:00:05'
  - service: script.turn_on
    entity_id: script.alarm_manual_triggered
  - delay: '00:00:30'
  - service: media_player.turn_off
    entity_id: media_player.amigo
