alias: Alarm Manual Pending
initial_state: 'true'
trigger:
  - platform: state
    entity_id: alarm_control_panel.seguridad_casa
    to: 'pending'
action:
  - service: notify.telegram_bacab_home_bot
    data_template:
      message: "Alarm! Pending {{ states('sensor.date_time') }}"
