alias: Alarm Manual Arm Home
initial_state: 'true'
trigger:
  - platform: state
    entity_id: alarm_control_panel.seguridad_casa
    to: 'armed_home'
action:
  - service: notify.telegram_bacab_home_bot
    data_template:
      message: "Alarm! Armed Home {{ states('sensor.date_time') }}"
