alias: Alarm Manual Triggered
initial_state: 'true'
trigger:
  - platform: state
    entity_id: alarm_control_panel.seguridad_casa
    to: 'triggered'
action:
  - service: notify.telegram_bacab_home_bot
    data_template:
      message: "Alarma activada {{ states('sensor.date_time') }}"
