alias: Alarm Manual Disarm
initial_state: 'true'
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm_manual
    to: 'disarmed'
action:
  - service: notify.telegram_bacab_home_bot
    data_template:
      message: "Alarm! Disarmed {{ states('sensor.date_time') }}"
