alias: Alarm Manual Armed Home Triggered
initial_state: 'true'
trigger:
  - platform: state
    entity_id: input_boolean.family_mode_alarm_test
    to: 'on'
condition:
  - condition: state
    entity_id: alarm_control_panel.seguridad_casa
    state: armed_home
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.seguridad_casa
