alias: Alarm Manual Arm Away
initial_state: 'true'
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm_manual
    to: 'armed_away'
action:
  - service: notify.telegram_bacab_home_bot
    data_template:
      message: "Alarm! Armed Away {{ states('sensor.date_time') }}"
