alias: Alarm Manual Armed Home Triggered
initial_state: 'true'
trigger:
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_01_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_02_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_49fc4604_on_off
    to: 'on'
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_f2eb4604_on_off
    to: 'on'
condition:
  - condition: state
    entity_id: alarm_control_panel.alarm_manual
    state: armed_home
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm_manual
