alias: Alarm Manual Armed Away Triggered
initial_state: 'true'
trigger:
  - platform: state
    entity_id: input_boolean.family_mode_alarm_test
    to: 'on'
condition:
  - condition: state
    entity_id: alarm_control_panel.alarm_manual
    state: armed_away
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm_manual
  - service: script.turn_on
    entity_id: script.alarm_manual_triggered
