alias: alwaysAI Simple Object Counter Motorcycle On Camera
initial_state: true
mode: queued
trigger:
  - platform: state
    entity_id: binary_sensor.alwaysai_simple_object_counter_motorcycle
    from: 'off'
    to: 'on'
condition:
  condition: time
  after: '22:00:00'
  before: '06:00:00'
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
action:
  - service: notify.telegram_bacab_home_bot
    data:
      title: alwaysAI Simple Object Counter
      message: "Motorcycle"
  - service: camera.record
    data_template:
      entity_id: camera.camara_exterior
      filename: '/config/www/media/night/{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 30
      lookback: 20
