alias: Simple Object Counter Person On Camera
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.alwaysai_simple_object_counter_person
    from: 'off'
    to: 'on'
condition:
  condition: time
  after: '22:00:00'
  before: '06:00:00'
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
action:
  - service: notify.telegram_bacab_home_bot
    data:
      title: alwaysAI Simple Object Counter
      message: "Person"
  - service: script.turn_on
    entity_id: script.camara_exterior_notificacion
