version: '3'
services:

  homeassistant:
    image: homeassistant/home-assistant
    container_name: bacabhome-homeassistant
    depends_on:
      - "influxdb"
    network_mode: host
    ports:
      - 8123:8123
    devices:
      - /dev/urandom:/dev/urandom
    restart: on-failure
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro

  influxdb:
    image: influxdb
    container_name: bacabhome-influxdb
    ports:
      - 8083:8083
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_ENABLED='true'
      - INFLUXDB_DB="home_assistant"
    restart: on-failure
    volumes:
      - bacabhome-influxdb-storage:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: bacabhome-grafana
    depends_on:
      - "influxdb"
    network_mode: host
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - bacabhome-grafana-storage:/var/lib/grafana


volumes:
  bacabhome-influxdb-storage:
  bacabhome-grafana-storage:
