version: '3'
services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: bacab-home-mosquitto
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    ports:
      - 1883:1883
    user: "1000:1000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - bacabhome-mosquitto-storage:/mosquitto/config:ro
      - bacabhome-mosquitto-storage:/mosquitto/data:rw
      - bacabhome-mosquitto-storage:/mosquitto/log:rw

  glances:
    image: docker.io/nicolargo/glances
    container_name: bacab-home-glances
    restart: on-failure
    pid: host
    environment:
      - TZ=America/Mexico_City
      - "GLANCES_OPT=-w"
    network_mode: host
    ports:
      - 61208:61208
      - 61209:61209
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  homeassistant:
    build:
      context: ./config/homeassistant/
      dockerfile: Dockerfile.homeassistant
    image: homeassistant/home-assistant
    container_name: bacab-home-homeassistant
    privileged: true
    restart: on-failure
    depends_on:
      - "influxdb"
      - "mosquitto"
      - "glances"
      - "doods"
    environment:
      - TZ=America/Mexico_City
    cap_add:
      - ALL
    pid: "host"
    ipc: "host"
    network_mode: "host"
    ports:
      - 8123:8123
    devices:
      - /dev/urandom:/dev/urandom
      - /dev
      - /dev/snd
      - /proc
      - /dev/dri/card1:/dev/dri/card0
      - /dev/dri/renderD129:/dev/dri/renderD128
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./homeassistant:/config
      - ./media:/config/www/media/:consistent
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/.X11-unix:/tmp/.X11-unix:consistent
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie:consistent

  influxdb:
    image: influxdb
    container_name: bacab-home-influxdb
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
      - INFLUXDB_ADMIN_ENABLED='true'
      - INFLUXDB_DB="home_assistant"
    network_mode: host
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - bacabhome-influxdb-storage:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: bacab-home-grafana
    restart: on-failure
    depends_on:
      - "influxdb"
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    ports:
      - 3000:3000
    volumes:
      - bacabhome-grafana-storage:/var/lib/grafana

  portainer:
    image: portainer/portainer
    container_name: bacab-home-portainer
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    ports:
      - 9000:9000
    volumes:
      - bacabhome-portainer-storage:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock

  nodered:
    build:
      context: ./config/nodered/
      dockerfile: Dockerfile.nodered
    image: nodered/node-red-docker:v8
    container_name: bacab-home-nodered
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    ports:
      - 1880:1880
    depends_on:
      - "homeassistant"
    user: root
    volumes:
      - bacabhome-nodered-storage:/data
      - /etc/localtime:/etc/localtime:ro

  netdata:
    image: netdata/netdata
    container_name: bacab-home-netdata
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
    entrypoint: ["echo", "Service disabled"]
    network_mode: host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  motioneye:
    image: cahna/motioneye
    container_name: bacab-home-motioneye
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    ports:
      - "8081:8081"
      - "8765:8765"
    volumes:
      - ./config/motioneye/etc:/etc/motioneye
      - ./media/motioneye/:/var/lib/motioneye

  plex:
    image: plexinc/pms-docker
    container_name: bacab-home-plex
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
      - PLEX_CLAIM=<claimToken>
    network_mode: host
    volumes:
      - ./config/plex/database:/config
      - ./config/plex/transcode:/transcode
      - ./media/:/data

  prometheus:
    image: prom/prometheus:0.18.0
    container_name: bacab-home-prometheus
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
    entrypoint: ["echo", "Service disabled"]
    network_mode: host
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'

  node-exporter:
    image: prom/node-exporter
    container_name: bacab-home-node-exporter
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
    entrypoint: ["echo", "Service disabled"]
    network_mode: host
    ports:
      - '9100:9100'
    cap_add:
      - SYS_PTRACE
      - SYS_TIME
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'

  hadockermon:
    image: philhawthorne/ha-dockermon
    container_name: bacab-home-ha-dockermon
    restart: always
    network_mode: host
    ports:
      - 8126:8126
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/ha-dockermon/:/config

  doods:
    image: snowzach/doods
    container_name: bacab-home-doods
    restart: always
    network_mode: host
    ports:
      - 8080:8080

  telegraf:
    image: telegraf:latest
    container_name: bacab-home-telegraf
    restart: always
    network_mode: host
    depends_on:
      - "influxdb"
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

volumes:
  bacabhome-mosquitto-storage:
  bacabhome-influxdb-storage:
  bacabhome-grafana-storage:
  bacabhome-portainer-storage:
  bacabhome-nodered-storage:
