version: '3'
services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: bacab-home-mosquitto
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    ports:
      - 1883:1883
    user: "1000:1000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - bacabhome-mosquitto-storage:/mosquitto/config:ro
      - bacabhome-mosquitto-storage:/mosquitto/data:rw
      - bacabhome-mosquitto-storage:/mosquitto/log:rw

  glances:
    image: docker.io/nicolargo/glances
    container_name: bacab-home-glances
    restart: on-failure
    pid: host
    environment:
      - TZ=America/Mexico_City
      - "GLANCES_OPT=-w"
    network_mode: host
    ports:
      - 61208:61208
      - 61209:61209
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  homeassistant:
    build:
      context: ./config/homeassistant/
      dockerfile: Dockerfile.homeassistant
    image: homeassistant/home-assistant
    container_name: bacab-home-homeassistant
    privileged: true
    restart: on-failure
    depends_on:
      - "influxdb"
      - "mosquitto"
      - "glances"
    environment:
      - TZ=America/Mexico_City
    cap_add:
      - ALL
    ipc: "host"
    network_mode: "host"
    ports:
      - 8123:8123
    devices:
      - /dev/urandom:/dev/urandom
      - /dev
      - /dev/snd
      - /proc
      - /dev/dri/card1:/dev/dri/card0
      - /dev/dri/renderD129:/dev/dri/renderD128
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./homeassistant:/config
      - ./media:/config/www/media/:consistent
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /tmp/.X11-unix:/tmp/.X11-unix:consistent
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie:consistent

  influxdb:
    image: influxdb
    container_name: bacab-home-influxdb
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
      - INFLUXDB_ADMIN_ENABLED='true'
      - INFLUXDB_DB="home_assistant"
    network_mode: host
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - bacabhome-influxdb-storage:/var/lib/influxdb

  nodered:
    build:
      context: ./config/nodered/
      dockerfile: Dockerfile.nodered
    image: nodered/node-red-docker:v8
    container_name: bacab-home-nodered
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    ports:
      - 1880:1880
    depends_on:
      - "homeassistant"
    user: root
    volumes:
      - bacabhome-nodered-storage:/data
      - /etc/localtime:/etc/localtime:ro

  motioneye:
    image: cahna/motioneye
    container_name: bacab-home-motioneye
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
    network_mode: host
    ports:
      - "8081:8081"
      - "8765:8765"
    volumes:
      - ./config/motioneye/etc:/etc/motioneye
      - ./media/motioneye/:/var/lib/motioneye

  plex:
    image: plexinc/pms-docker
    container_name: bacab-home-plex
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
      - PLEX_CLAIM=<claimToken>
    network_mode: host
    volumes:
      - ./config/plex/database:/config
      - ./config/plex/transcode:/transcode
      - ./media/:/data:consistent

  hadockermon:
    image: philhawthorne/ha-dockermon
    container_name: bacab-home-ha-dockermon
    restart: always
    network_mode: host
    ports:
      - 8126:8126
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/ha-dockermon/:/config

  grafana:
    image: grafana/grafana
    container_name: lak-grafana
    restart: on-failure
    depends_on:
      - "influxdb"
    environment:
      - TZ=America/Mexico_City
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource,yesoreyeram-boomtable-panel
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
      - GF_PATHS_PROVISIONING=/usr/share/grafana/conf/provisioning/
    network_mode: host
    ports:
      - 3000:3000
    volumes:
      - bacabhome-grafana-volume:/var/lib/grafana
      - ./grafana/provisioning/datasources:/usr/share/grafana/conf/provisioning/datasources:rw
      - ./grafana/provisioning/notifiers:/usr/share/grafana/conf/provisioning/notifiers:rw
      - ./grafana/provisioning/dashboards:/usr/share/grafana/conf/provisioning/dashboards:rw

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: lak-image-renderer
    restart: on-failure
    environment:
      ENABLE_METRICS: "true"
    network_mode: host
    ports:
      - 8081:8081

volumes:
  bacabhome-mosquitto-storage:
  bacabhome-influxdb-storage:
  bacabhome-grafana-storage:
  bacabhome-portainer-storage:
  bacabhome-nodered-storage:
  bacabhome-grafana-volume:
