alias: alwaysAI Object Detector And Classifier Face
initial_state: 'true'
trigger:
- platform: event
  event_type: folder_watcher
  event_data:
    event_type: modified
action:
  - service: local_file_update_file_path
    data_template:
      entity_id: camera.alwaysai_object_detector_and_classifier_face
      file_path: /config/www/media/applications/alwaysai_object_detector_and_classifier.jpg
