alias: alwaysAI People Counter
initial_state: 'true'
trigger:
- platform: event
  event_type: folder_watcher
  event_data:
    event_type: modified
action:
  - service: local_file.update_file_path
    data_template:
      entity_id: camera.alwaysai_people_counter
      file_path: /config/www/media/applications/alwaysai_people_counter.jpg
