{
 "title": "Bacab Home Main",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Home", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Conmmute Time", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 1 }, "content": "\n\n\n" },
  { "title": "Environment", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 3, "y": 1 }, "content": "\n\n\n" },
  { "title": "Motion On", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 6, "y": 1 }, "content": "\n\n\n" },
  { "title": "Lights On", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 9, "y": 1 }, "content": "\n\n\n" },
  { "title": "Balam Weekly", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 12, "y": 1 }, "content": "\n\n\n" },
  { "title": "Battery Levels", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 15, "y": 1 }, "content": "\n\n\n" },
  {
   "title": "School",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "School",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "here_travel_time_home_to_school"
      }
     ]
    }
   ]
  },
  {
   "title": "House Temperature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "home_mean_temperature" }
     ]
    }
   ]
  },
  {
   "title": "Now",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "binary_sensor.template_all_motion_on",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "template_all_motion_on" }
     ]
    }
   ]
  },
  {
   "title": "Today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "all_lights_on_today" }
     ]
    }
   ]
  },
  {
   "title": "Home",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "person_balam_home_week" }
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "home_mean_battery" }
     ]
    }
   ]
  },
  {
   "title": "Work",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "Work",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "here_travel_time_home_to_work" }
     ]
    }
   ]
  },
  {
   "title": "House Humidity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "home_mean_humidity" }
     ]
    }
   ]
  },
  {
   "title": "Today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "all_motion_on_today" }
     ]
    }
   ]
  },
  {
   "title": "Yesterday",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "all_lights_on_yesterday" }
     ]
    }
   ]
  },
  {
   "title": "Work",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "person_balam_work_week" }
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "content": "\n\n\n\n" },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "content": "\n\n\n\n" },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
     "format": "d",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "days",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "uptime" }
       ]
      }
     ]
    },
    {
     "title": "Internet",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "binary_sensor.ping_google_public_dns",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "ping_google_public_dns" }
       ]
      }
     ]
    },
    {
     "title": "Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensor.glances_containers_active",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "glances_containers_active" }
       ]
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "%",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "glances_ram_used_percent" }
       ]
      }
     ]
    },
    {
     "title": "RAM Free",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
     "format": "gbytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "MiB",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "glances_ram_free" }
       ]
      }
     ]
    },
    {
     "title": "Disk Free",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
     "format": "gbytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "GiB",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "disk_free_home" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "content": "\n\n\n\n" },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "CPU Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "%",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "glances_cpu_used" }
       ]
      },
      {
       "alias": "Containers CPU Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "%",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "glances_containers_cpu_used" }
       ]
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "RAM Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "MiB",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "glances_ram_used" }
       ]
      },
      {
       "alias": "Containers RAM Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "MiB",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "glances_containers_ram_used" }
       ]
      }
     ]
    },
    {
     "title": "Speedtest",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "Mbits" }
     ],
     "targets": [
      {
       "alias": "Download",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Mbit/s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "speedtest_download" }
       ]
      },
      {
       "alias": "Upload",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Mbit/s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "speedtest_upload" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Energy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "content": "\n\n\n\n" },
    {
     "title": "Lights On",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 12 },
     "targets": [
      {
       "alias": "Yesterday",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "h",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "all_lights_on_yesterday" }
       ]
      },
      {
       "alias": "Today",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "h",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "all_lights_on_today" }
       ]
      },
      {
       "alias": "Week",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "h",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "all_lights_on_week" }
       ]
      },
      {
       "alias": "Month",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "h",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "all_lights_on_month" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "content": "\n\n\n\n" }
   ]
  },
  {
   "title": "Plants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "content": "\n\n\n\n" },
    {
     "title": "Nopal",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
     "format": "h",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "h",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "plant_nopal_01_state_ok" }
       ]
      }
     ]
    },
    {
     "title": "Nopal",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
     "format": "h",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "h",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "entity_id",
         "operator": "=",
         "value": "plant_palma_chamedor_02_state_ok"
        }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "content": "\n\n\n\n" },
    {
     "title": "Moisture",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "humidity" }
     ],
     "targets": [
      {
       "alias": "Palma",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "%",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "miflora_01_moisture" }
       ]
      },
      {
       "alias": "Nopal",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "%",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "miflora_02_moisture" }
       ]
      }
     ]
    },
    {
     "title": "Conductivity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "µS/cm" }
     ],
     "targets": [
      {
       "alias": "Palma",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "µS/cm",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "miflora_01_conductivity" }
       ]
      },
      {
       "alias": "Nopal",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "µS/cm",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "miflora_02_conductivity" }
       ]
      }
     ]
    },
    {
     "title": "Light",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "lux" }
     ],
     "targets": [
      {
       "alias": "Palma",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lx",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "miflora_01_light_intensity" }
       ]
      },
      {
       "alias": "Nopal",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lx",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "miflora_02_light_intensity" }
       ]
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "°C",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "miflora_01_temperature" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "°C",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "miflora_02_temperature" }
       ]
      }
     ]
    },
    {
     "title": "Plants Battery",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "Palma",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "%",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "miflora_01_battery" }
       ]
      },
      {
       "alias": "Nopal",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "%",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "entity_id", "operator": "=", "value": "miflora_02_battery" }
       ]
      }
     ]
    }
   ]
  }
 ]
}