# prometheus.yml

global:

  scrape_interval: 5s
  external_labels:
    monitor: 'bacab-home-monitor'

scrape_configs:

    - job_name: 'prometheus'
      target_groups:
        - targets: ['localhost:9090']

    - job_name: 'netdata'
      metrics_path: /api/v1/allmetrics
      params:
        format: [ prometheus ]
      target_groups:
        - targets: ['172.17.0.1:19999']
