FROM xe1gyq/openvino

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ARG OPENVINO_INSTALL=/opt/intel/computer_vision_sdk
ENV OPENVINO_INSTALL=/opt/intel/computer_vision_sdk

ENV TIMEZONE America/Mexico_City
USER root

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends \
    vim \
    libssl-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade \
    paho-mqtt

RUN apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home/user
RUN chown user /home/user
USER user

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh"

RUN git clone https://github.com/intel-iot-devkit/parking-lot-counter-cpp.git && \
    git clone https://github.com/bacabhome/other.git

RUN cp /home/user/other/parking-lot-counter-cpp/main.cpp /home/user/parking-lot-counter-cpp/src/ && \
    cp /home/user/other/parking-lot-counter-cpp/mqtt.cpp /home/user/parking-lot-counter-cpp/src/ && \
    cp /home/user/other/parking-lot-counter-cpp/mqtt.h /home/user/parking-lot-counter-cpp/src/

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh && \
    mkdir /home/user/parking-lot-counter-cpp/build && \
    cd /home/user/parking-lot-counter-cpp/build && \
    cmake .. && \
    make"

RUN mkdir /home/user/parking-lot-counter-cpp/resources && \
    cd /home/user/parking-lot-counter-cpp/resources && \
    wget https://github.com/intel-iot-devkit/sample-videos/raw/master/car-detection.mp4

ADD --chown=1000:1000 main.sh /home/user/
RUN /bin/bash -c 'chmod +x /home/user/main.sh'
RUN /bin/bash -c '/home/user/main.sh'

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh"
RUN echo "source $OPENVINO_INSTALL/bin/setupvars.sh" >> /home/user/.bashrc

CMD ["/home/user/main.sh"]
