FROM xe1gyq/openvino

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ARG OPENVINO_INSTALL=/opt/intel/computer_vision_sdk

ENV TIMEZONE America/Mexico_City
USER root

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends \
    vim && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade \
    pyyaml

RUN apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home/user
RUN chown user /home/user
USER user

RUN git clone https://github.com/intel-iot-devkit/store-traffic-monitor-python.git && \
    git clone https://github.com/bacabhome/other.git

RUN cd $OPENVINO_INSTALL/deployment_tools/model_downloader && \
    sudo -E ./downloader.py --name mobilenet-ssd

RUN cd $OPENVINO_INSTALL/deployment_tools/model_optimizer && \
    ./mo_caffe.py --input_model $OPENVINO_INSTALL/deployment_tools/model_downloader/object_detection/common/mobilenet-ssd/caffe/mobilenet-ssd.caffemodel -o $HOME/store-traffic-monitor-python/resources
   #./mo_caffe.py --input_model $OPENVINO_INSTALL/deployment_tools/model_downloader/object_detection/common/mobilenet-ssd/caffe/mobilenet-ssd.caffemodel -o $HOME/store-traffic-monitor-python/resources --data_type FP16

RUN cp /home/user/other/store-traffic-monitor-python/store-traffic-monitor.py /home/user/store-traffic-monitor-python

RUN cd /home/user/store-traffic-monitor-python && \
    python video_downloader.py

ADD --chown=1000:1000 main.sh /home/user/
RUN /bin/bash -c 'chmod +x /home/user/main.sh'
RUN /bin/bash -c '/home/user/main.sh'

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh"
RUN echo "source $OPENVINO_INSTALL/bin/setupvars.sh" >> /home/user/.bashrc

CMD ["/home/user/main.sh"]
