alias: Application Restricted Zone Notifier Python
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.application_restricted_zone_notifier_python
  from: 'off'
  to: 'on'
action:
  - service: camera.snapshot
    data:
      entity_id: camera.amcrest_camera_01
      filename: '/config/www/media/application/restricted_zone_notifier_python.jpg'
  - service: camera.record
    data_template:
      entity_id: camera.amcrest_camera_01
      filename: '/config/www/media/application/rznp_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 30
      lookback: 2
  - service: camera.snapshot
    data:
      entity_id: camera.local_file_restricted_zone_notifier_python
      filename: '/config/www/media/application/rznp_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
