homeassistant:
  # Name of the location where Home Assistant is running
  name: Bacab Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_altitude

  # metric for Metric, imperial for Imperial
  unit_system: metric

  external_url: !secret external_url

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Mexico_City

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.192.0/24
        - 192.168.0.0/24
        - 192.168.1.0/24
      allow_bypass_login: true
    - type: homeassistant

  whitelist_external_dirs:
    - '/config/www/media/cameras'
    - '/config/www/media/photos/azotea'
    - '/config/www/media/photos/cocheras'
    - '/config/www/media/photos/entrada'
    - '/config/www/media/photos/exterior'
    - '/config/www/media/photos/lavadero'
    - '/config/www/media/photos/toldo'
    - '/config/www/media/videos/azotea'
    - '/config/www/media/videos/cocheras'
    - '/config/www/media/videos/entrada'
    - '/config/www/media/videos/exterior'
    - '/config/www/media/videos/lavadero'
    - '/config/www/media/videos/toldo'

  # Customizing entities
  customize: !include_dir_merge_named components/customize/

  # Load packages
  packages: !include_dir_named components/packages
