homeassistant:
  # Name of the location where Home Assistant is running
  name: Bacab Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_altitude

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Mexico_City

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.192.0/24
        - 192.168.0.0/24
        - 192.168.1.0/24
      allow_bypass_login: true
    - type: homeassistant

  whitelist_external_dirs:
    - '/config/www/media/application/'
    - '/config/www/media/cameras/'
    - '/config/www/media/deepstack/'
    - '/config/www/media/doods/'
    - '/config/www/media/house/'
    - '/config/www/media/motioneye/'

  # Customizing entities
  customize: !include_dir_merge_named components/customize/

  # Load packages
  packages: !include_dir_named components/packages

hacs:
  token: !secret hacs_token
