title: Bacab Home

resources: !include lovelace/resources.yaml

views:

  - !include lovelace/home.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/plants.yaml
  - !include lovelace/downstairs.yaml
  - !include lovelace/bedrooms.yaml
  - !include lovelace/livingroom.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/power.yaml
  - !include lovelace/server.yaml
  - !include lovelace/cameras.yaml
  - !include lovelace/science.yaml
  - !include lovelace/custom.yaml
