title: Bacab Home

resources:
    - url: /local/bignumber-card.js?v=0.0.1
      type: js
    - url: /local/monster-card.js?v=0.2.3
      type: js

views:

  - icon: mdi:home-heart
    title: Sweet Home
    cards:

      - type: markdown
        title: Welcome to Bacab Home!
        content: >
          Bacab? Old god of the interior of the earth and of thunder, sky-carrier, fourfold.
          Today? a Smart Home!

      - type: shopping-list
        title: Shopping List

  - icon: mdi:cctv
    id: Camera
    title: Camera
    panel: false
    cards:

      - type: picture-glance
        title: Camera FFmpeg
        entities:
          - binary_sensor.ffmpeg_motion
          - binary_sensor.mqtt_binary_sensor
          - sensor.dark_sky_apparent_temperature
          - sensor.mqtt_sensor
        camera_image: camera.ffmpeg

      - type: picture-glance
        title: Camera Mjpeg
        entities:
          - binary_sensor.ffmpeg_motion
          - binary_sensor.mqtt_binary_sensor
          - sensor.dark_sky_apparent_temperature
          - sensor.mqtt_sensor
        camera_image: camera.mjpeg_camera

  - icon: mdi:weather-cloudy
    id: Weather
    title: Weather
    panel: false
    cards:

      - type: weather-forecast
        entity: weather.dark_sky

      - type: entities
        title: Dark Sky
        show_header_toggle: false
        entities:
          - weather.dark_sky

      - type: iframe
        url: https://embed.windy.com/embed2.html?lat=23.564&lon=-102.305&zoom=5&level=surface&overlay=rain&menu=&message=true&marker=&calendar=12&pressure=&type=map&location=coordinates&detail=&detailLat=20.724&detailLon=-103.385&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1
        aspect_ratio: 50%

      - type: entities
        title: Dark Sky
        entities:
          - entity: sensor.dark_sky_precip_probability
            name: Precipitation Probability
          - entity: sensor.dark_sky_temperature
            name: Temperature
          - entity: sensor.dark_sky_wind_speed
            name: Wind Speed
          - entity: sensor.dark_sky_cloud_coverage
            name: Cloud Coverage
          - entity: sensor.dark_sky_humidity
            name: Humidity
          - entity: sensor.dark_sky_visibility
            name: Visibility
          - entity: sensor.dark_sky_daytime_high_temperature_0
            name: Daytime High Temperature
          - entity: sensor.dark_sky_overnight_low_temperature_0
            name: Overnight Low Temperature

  - icon: mdi:chart-bar
    id: Sensors
    title: Sensors
    cards:

      - type: sensor
        entity: sensor.glances_cpu_load
        name: CPU Load
        graph: line
        unit: '%'
        detail: 2

      - type: sensor
        entity: sensor.glances_ram_used
        name: RAM Used
        graph: line
        unit: '%'
        detail: 2

      - type: glance
        columns: 2
        show_state: false
        entities:
          - entity: sensor.glances_cpu_load
            name: CPU Load
          - entity: sensor.glances_ram_used
            name: RAM Used

      - type: gauge
        entity: sensor.glances_cpu_load
        name: CPU Load
        unit: '%'
        severity:
          green: 0
          yellow: 65
          red: 85

      - type: gauge
        entity: sensor.glances_ram_used
        name: RAM Used Load
        unit: '%'
        severity:
          green: 0
          yellow: 65
          red: 85

      - type: entities
        title: Entities Glances
        show_header_toggle: false
        entities:
          - entity: sensor.glances_cpu_load
            name: CPU Load
          - entity: sensor.glances_ram_used
            name: RAM Used
          - type: divider

      - type: history-graph
        title: History Graph Glances
        entities:
          - sensor.glances_cpu_load
          - sensor.glances_ram_used

      - type: picture-elements
        image: /local/pictures/ui-lovelace/2018072901.jpg
        title: Picture Elements Glances
        elements:

          - type: state-icon
            entity: sensor.glances_cpu_load
            style:
              top: 10%
              left: 10%
              color: white

          - type: state-icon
            entity: sensor.glances_ram_used
            style:
              top: 10%
              left: 20%
              color: white

          - type: icon
            icon: mdi:docker
            entity: sensor.glances_containers_cpu_used
            tap_action: none
            style:
              top: 10%
              left: 75%            
              color: white

          - type: state-label
            entity: sensor.glances_containers_cpu_used
            tap_action: more-info
            style:
              top: 20%
              left: 75%
              color: white

          - type: icon
            icon: mdi:memory
            entity: sensor.glances_ram_used
            tap_action: none
            style:
              top: 10%
              left: 90%
              color: white

          - type: state-label
            entity: sensor.glances_ram_used
            tap_action: more-info
            style:
              top: 20%
              left: 90%
              color: white

  - icon: mdi:web
    id: Web Links
    title: Web Links
    cards:

      - type: entities
        title: Services
        show_header_toggle: false
        entities:
          - type: weblink
            name: Home Assistant
            url: https://www.home-assistant.io/
            icon: mdi:home-assistant
          - type: weblink
            name: Grafana
            url: http://127.0.0.1:9000
          - type: weblink
            name: Portainer
            url: http://127.0.0.1:3000


      - type: entities
        title: Services
        entities:
          - entity: weblink.grafana
            name: Grafana

      - type: iframe
        url: http://127.0.0.1:3000/d/IkHMgesmz/hello-world?orgId=1&from=now-6h&to=now&panelId=1
        aspect_ratio: 100%

      - type: iframe
        url: http://127.0.0.1:9000/
        aspect_ratio: 100%

  - icon: mdi:toggle-switch
    id: Binary Sensors
    title: Binary Sensors
    cards:

      - type: entities
        title: Internet
        show_header_toggle: false
        entities:
          - entity: binary_sensor.ping_binary_sensor
            name: Google Public DNS

      - type: glance
        columns: 2
        show_state: false
        entities:
          - entity: binary_sensor.ffmpeg_motion
            name: FFmpeg Motion
          - entity: binary_sensor.mqtt_binary_sensor
            name: Mqtt

      - type: picture-glance
        title: MQTT
        show_header_toggle: false
        entities:
          - binary_sensor.ffmpeg_motion
          - binary_sensor.mqtt_binary_sensor
        image: /local/pictures/ui-lovelace/2018072201.jpg

      - type: picture-glance
        title: MQTT
        show_header_toggle: false
        entities:
          - binary_sensor.ffmpeg_motion
          - binary_sensor.mqtt_binary_sensor
        image: /local/pictures/ui-lovelace/2018073001.jpg
        state_image:
          "on": /local/pictures/ui-lovelace/2018072901.jpg
          "off": /local/pictures/ui-lovelace/2018072902.jpg
        entity: binary_sensor.mqtt_binary_sensor

  - icon: mdi:image-filter
    id: Image Processing
    title: Image Processing
    cards:

      - type: entities
        title: Face Detect
        entities:
          - entity: image_processing.dlib_face_detect_ffmpeg
            name: FFmpeg
          - entity: image_processing.dlib_face_detect_mjpeg_camera
            name: Mjpeg

  - icon: mdi:switch
    id: Switches
    title: Switches
    cards:

      - type: entities
        title: Mqtt
        show_header_toggle: false
        entities:
          - switch.mqtt_switch

      - type: picture
        image: /local/pictures/ui-lovelace/2018072903.jpg
        service: switch.toggle
        service_data:
          entity_id: switch.mqtt_switch

      - type: picture-entity
        entity: switch.mqtt_switch
        state_image:
          "on": /local/pictures/ui-lovelace/2018073001.jpg
          "off": /local/pictures/ui-lovelace/2018073002.jpg

  - icon: mdi:oil-temperature
    if: Custom
    title: Custom
    cards:

      - type: custom:bignumber-card
        title: Sensor MQTT
        entity: sensor.mqtt_sensor
        scale: 30px
        from: bottom
        min: 0
        max: 100
        severity:
          - value: 70
            style: 'var(--label-badge-green)'
          - value: 90
            style: 'var(--label-badge-yellow)'
          - value: 100
            style: 'var(--label-badge-red)'

      - type: custom:monster-card
        card:
          type: entities
          title: Broken Things
          show_header_toggle: false
        filter:
          include:
            - state: "unknown"
          exclude:
            - entity_id: group.*

      - type: custom:monster-card
        card:
          type: glance
          title: Monster
        filter:
          include:
            - domain: device_tracker
              attributes:
                battery: '< 25'
                source_type: gps
