title: Bacab Home

resources: !include lovelace/resources.yaml

views:

  - !include lovelace/home.yaml
  - !include lovelace/cameras.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/sensors.yaml

  - icon: mdi:web
    id: Web Links
    title: Web Links
    cards:

      - type: entities
        title: Services
        show_header_toggle: false
        entities:
          - type: weblink
            name: Home Assistant
            url: https://www.home-assistant.io/
            icon: mdi:home-assistant
          - type: weblink
            name: Grafana
            url: !secret services_grafana_url
          - type: weblink
            name: Portainer
            url: !secret services_portainer_url


      - type: entities
        title: Services
        entities:
          - entity: weblink.grafana
            name: Grafana

      - type: iframe
        url: !secret services_grafana_url
        aspect_ratio: 100%

      - type: iframe
        url: !secret services_portainer_url
        aspect_ratio: 100%

  - icon: mdi:toggle-switch
    id: Binary Sensors
    title: Binary Sensors
    cards:

      - type: entities
        title: Internet
        show_header_toggle: false
        entities:
          - entity: binary_sensor.ping_binary_sensor
            name: Google Public DNS

      - type: glance
        columns: 2
        show_state: false
        entities:
          - entity: binary_sensor.ffmpeg_motion
            name: FFmpeg Motion
          - entity: binary_sensor.mqtt_binary_sensor
            name: Mqtt

      - type: picture-glance
        title: MQTT
        show_header_toggle: false
        entities:
          - binary_sensor.ffmpeg_motion
          - binary_sensor.mqtt_binary_sensor
        image: /local/pictures/ui-lovelace/2018072201.jpg

      - type: picture-glance
        title: MQTT
        show_header_toggle: false
        entities:
          - binary_sensor.ffmpeg_motion
          - binary_sensor.mqtt_binary_sensor
        image: /local/pictures/ui-lovelace/2018073001.jpg
        state_image:
          "on": /local/pictures/ui-lovelace/2018072901.jpg
          "off": /local/pictures/ui-lovelace/2018072902.jpg
        entity: binary_sensor.mqtt_binary_sensor

  - icon: mdi:image-filter
    id: Image Processing
    title: Image Processing
    cards:

      - type: entities
        title: Face Detect
        entities:
          - entity: image_processing.dlib_face_detect_ffmpeg
            name: FFmpeg
          - entity: image_processing.dlib_face_detect_mjpeg_camera
            name: Mjpeg

  - icon: mdi:switch
    id: Switches
    title: Switches
    cards:

      - type: entities
        title: Mqtt
        show_header_toggle: false
        entities:
          - switch.mqtt_switch

      - type: picture
        image: /local/pictures/ui-lovelace/2018072903.jpg
        service: switch.toggle
        service_data:
          entity_id: switch.mqtt_switch

      - type: picture-entity
        entity: switch.mqtt_switch
        state_image:
          "on": /local/pictures/ui-lovelace/2018073001.jpg
          "off": /local/pictures/ui-lovelace/2018073002.jpg

  - icon: mdi:oil-temperature
    if: Custom
    title: Custom
    cards:

      - type: custom:bignumber-card
        title: Sensor MQTT
        entity: sensor.mqtt_sensor
        scale: 30px
        from: bottom
        min: 0
        max: 100
        severity:
          - value: 70
            style: 'var(--label-badge-green)'
          - value: 90
            style: 'var(--label-badge-yellow)'
          - value: 100
            style: 'var(--label-badge-red)'

      - type: custom:monster-card
        card:
          type: entities
          title: Broken Things
          show_header_toggle: false
        filter:
          include:
            - state: "unknown"
          exclude:
            - entity_id: group.*

      - type: custom:monster-card
        card:
          type: glance
          title: Monster
        filter:
          include:
            - domain: device_tracker
              attributes:
                battery: '< 25'
                source_type: gps
