title: Bacab Home

resources: !include lovelace/resources.yaml

views:

  - !include lovelace/home.yaml
  - !include lovelace/wio_link_01.yaml
  - !include lovelace/wio_link_02.yaml
  - !include lovelace/wio_link_03.yaml
