title: Bacab Home

resources: !include lovelace/resources.yaml

views:

  - !include lovelace/home.yaml
  - !include lovelace/server.yaml
  - !include lovelace/cameras.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/custom.yaml
