title: Bacab Home

resources: !include lovelace/resources.yaml

views:

  - !include lovelace/home.yaml
  - !include lovelace/cameras.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/sensors.yaml
  - !include lovelace/weblinks.yaml
  - !include lovelace/binary_sensors.yaml
  - !include lovelace/image_processing.yaml
  - !include lovelace/switches.yaml

  - icon: mdi:oil-temperature
    if: Custom
    title: Custom
    cards:

      - type: custom:bignumber-card
        title: Sensor MQTT
        entity: sensor.mqtt_sensor
        scale: 30px
        from: bottom
        min: 0
        max: 100
        severity:
          - value: 70
            style: 'var(--label-badge-green)'
          - value: 90
            style: 'var(--label-badge-yellow)'
          - value: 100
            style: 'var(--label-badge-red)'

      - type: custom:monster-card
        card:
          type: entities
          title: Broken Things
          show_header_toggle: false
        filter:
          include:
            - state: "unknown"
          exclude:
            - entity_id: group.*

      - type: custom:monster-card
        card:
          type: glance
          title: Monster
        filter:
          include:
            - domain: device_tracker
              attributes:
                battery: '< 25'
                source_type: gps
