title: Bacab Home Life

views:

  - !include lovelace/home.yaml
  - !include lovelace/cameras.yaml
  - !include lovelace/security.yaml
  - !include lovelace/perimetro.yaml
  - !include lovelace/cast.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/server.yaml
