alias: Applications OpenVINO Restricted Zone Notifier Python
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.applications_openvino_restricted_zone_notifier_python
  from: 'off'
  to: 'on'
action:
  - service: camera.snapshot
    data:
      entity_id: camera.ffmpeg_camera_01
      filename: '/config/www/media/applications/openvino/restricted_zone_notifier_python.jpg'
  - service: camera.record
    data_template:
      entity_id: camera.ffmpeg_camera_01
      filename: '/config/www/media/applications/openvino/rznp_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 30
      lookback: 2
  - service: script.turn_on
    entity_id: script.notification_light_person
  - service: camera.snapshot
    data:
      entity_id: camera.local_file_restricted_zone_notifier_python
      filename: '/config/www/media/applications/openvino/rznp_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
  - service: notify.telegram_bacab_home_bot
    data_template:
      message: "Warning! Restricted Zone Notifier {{ states('sensor.date_time') }}"
  - service: notify.telegram_bacab_home_bot
    data:
      title: 'Restricted Zone Notifier'
      message: "This is it..."
      data:
        photo:
          - file: '/config/www/media/applications/openvino/restricted_zone_notifier_python.jpg'
            caption: Person via Fffmpeg Camera 01

