version: '3.7'
services:

  mjpeg-streamer:
    build:
      context: ./mjpeg-streamer/
      dockerfile: Dockerfile.mjpeg-streamer
      args:
        - STREAMING_PORT="8080"
    image: xe1gyq/mjpeg-streamer
    container_name: bacab-home-mjpeg-streamer
    environment:
      - TZ=America/Mexico_City
      - STREAMING_PORT=8080
    ports:
      - 8080:8080
    devices:
      - /dev/video0

  gstreamer:
    build:
      context: ./gstreamer/
      dockerfile: Dockerfile.gstreamer
      args:
        - STREAMING_PORT="5000"
    image: xe1gyq/gstreamer
    container_name: bacab-home-gstreamer
    environment:
      - TZ=America/Mexico_City
      - STREAMING_PORT=5000
    ports:
      - 5000:5000
    devices:
      - /dev/video0

  opencv:
    build:
      context: ./opencv/
      dockerfile: Dockerfile.opencv
    image: xe1gyq/opencv
    container_name: bacab-home-opencv
    environment:
      - TZ=America/Mexico_City
    devices:
      - /dev/video0

  yolo:
    build:
      context: ./yolo/
      dockerfile: Dockerfile.yolo
    image: xe1gyq/yolo
    container_name: bacab-home-yolo
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - STREAMING_PORT=5000
      - DISPLAY_IP=172.17.0.1
      - DISPLAY_PORT=5100
    ports:
      - 5000:5000
      - 5100:5100
    devices:
      - /dev/video0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  haarcascades:
    build:
      context: ./haarcascades/
      dockerfile: Dockerfile.haarcascades
    image: xe1gyq/haarcascades
    container_name: bacab-home-haarcascades
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - NAME=Demo
      - STREAMING_PORT=5000
      - DISPLAY_IP=172.17.0.1
      - DISPLAY_PORT=5100
    entrypoint:
      - /home/user/main.sh
    command: ["Demo", "5000", "172.17.0.1", "5100"]
    ports:
      - 5000:5000
    devices:
      - /dev/video0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
