alias: Device Tracker Life360 Balam Zone Work Leaves
initial_state: 'true'
trigger:
  - platform: zone
    event: leave
    zone: zone.work
    entity_id: device_tracker.life360_balam
action:
  - service: media_player.volume_set
    entity_id:
    - media_player.amigo
    data:
      volume_level: 0.50
  - service: media_player.play_media
    entity_id: media_player.amigo
    data:
      media_content_id: "http://smrtho.us/storage/startup.mp3"
      media_content_type: "audio/mp3"
  - service: tts.google_translate_say
    entity_id: media_player.amigo
    data_template:
      message: >-
                 Balam ha salido del trabajo.
      language: 'es'
