alias: alwaysAI Simple Object Counter Motorcycle
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.alwaysai_simple_object_counter_motorcycle
  from: 'off'
  to: 'on'
action:
  - service: camera.snapshot
    data:
      entity_id: camera.camara_exterior
      filename: '/config/www/media/applications/alwaysai_simple_object_counter_motorcycle.jpg'
  - service: camera.record
    data_template:
      entity_id: camera.camara_exterior
      filename: '/config/www/media/applications/alwaysai/motorcycle/{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 30
      lookback: 20
  - service: camera.snapshot
    data:
      entity_id: camera.alwaysai_simple_object_counter_bicycle
      filename: '/config/www/media/applications/alwaysai/motorcycle/{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
  - service: notify.telegram_bacab_home_bot
    data:
      title: 'alwaysAI Simple Object Counter'
      message: "Motorcycle"
      data:
        photo:
          - file: '/config/www/media/applications/alwaysai_simple_object_counter_motorcycle.jpg'
            caption: Motorcycle
