alias: alwaysAI Simple Object Counter Person
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.alwaysai_simple_object_counter_person
  from: 'off'
  to: 'on'
action:
  - service: camera.snapshot
    data:
      entity_id: camera.camara_exterior
      filename: '/config/www/media/applications/alwaysai_simple_object_counter_person.jpg'
  - service: camera.record
    data_template:
      entity_id: camera.camara_exterior
      filename: '/config/www/media/applications/alwaysai/{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 60
      lookback: 15
  - service: camera.snapshot
    data:
      entity_id: camera.alwaysai_simple_object_counter_person
      filename: '/config/www/media/applications/alwaysai/{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
  - service: notify.telegram_bacab_home_bot
    data_template:
      message: "Warning! Simple Object Counter Person {{ states('sensor.date_time') }}"
  - service: notify.telegram_bacab_home_bot
    data:
      title: 'alwaysAI Simple Object Counter'
      message: "Person"
      data:
        photo:
          - file: '/config/www/media/applications/alwaysai_simple_object_counter_person.jpg'
            caption: Person
