alias: OpenVINO Restricted Zone Notifier Python
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.openvino_restricted_zone_notifier_python
  from: 'off'
  to: 'on'
action:
  - service: camera.snapshot
    data:
      entity_id: camera.camara_azotea
      filename: '/config/www/media/applications/openvino_restricted_zone_notifier_python.jpg'
  - service: camera.record
    data_template:
      entity_id: camera.camara_azotea
      filename: '/config/www/media/applications/openvino/{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 30
      lookback: 20
  - service: camera.snapshot
    data:
      entity_id: camera.openvino_restricted_zone_notifier_python
      filename: '/config/www/media/applications/openvino/{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
  - service: notify.telegram_bacab_home_bot
    data_template:
      message: "Warning! Restricted Zone Notifier {{ states('sensor.date_time') }}"
  - service: notify.telegram_bacab_home_bot
    data:
      title: 'OpenVINO Restricted Zone Notifier'
      message: "Person"
      data:
        photo:
          - file: '/config/www/media/applications/openvino_restricted_zone_notifier_python.jpg'
            caption: Person via Restricted Zone Notifier
