alias: Hue Outdoor Motion Sensor 01 On Ffmpeg Camera 01
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.hue_outdoor_motion_sensor_01_motion
    to: 'on'
action:
  - service: script.turn_on
    entity_id: script.ffmpeg_camera_01_capture
  - service: camera.record
    data_template:
      entity_id: camera.ffmpeg_camera_01
      filename: '/config/www/media/cameras/videos/ffmpeg_camera_01_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 60
      lookback: 10
