alias: Hue Outdoor Motion Sensor 01 On Ffmpeg Camera 01
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.hue_outdoor_motion_sensor_01_motion
    to: 'on'
action:
  - service: script.turn_on
    entity_id: script.ffmpeg_camera_01_capture
