alias: Hue Motion Sensor 02 On Doods
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.hue_motion_sensor_02_motion
    to: 'on'
action:
  - service: image_processing.scan
    data:
      entity_id: image_processing.doods_local_file_ffmpeg_camera_02 
