alias: Hue Outdoor Motion Sensor 01 On For Telegram
initial_state: 'true'
trigger:
  platform: state
  entity_id: binary_sensor.hue_outdoor_motion_sensor_01_motion
  to: 'on'
  for:
    seconds: 60
action:
  - service: camera.snapshot
    data:
      entity_id: camera.ffmpeg_camera_01
      filename: '/config/www/media/cameras/ffmpeg_camera_01.jpg'
  - service: notify.telegram_bacab_home_bot
    data_template:
      message: "Warning! Motion on threshold exceeded! {{ states('sensor.date_time') }}"
  - service: notify.telegram_bacab_home_bot
    data:
      title: 'Motion On For 60 Seconds'
      message: "This is it..."
      data:
        photo:
          - file: '/config/www/media/cameras/ffmpeg_camera_01.jpg'
            caption: 30 seconds! via Ffmpeg Camera 01
