alias: FFmpeg Camera 02 Cast Play Off
initial_state: 'true'
trigger:
- platform: state
  entity_id: input_boolean.ffmpeg_camera_02_cast
  from: 'on'
  to: 'off'
action:
  - service: media_player.turn_off
    entity_id: media_player.eek
