alias: Folder Watcher Modified Lovelace
initial_state: 'true'
trigger:
- platform: event
  event_type: folder_watcher
  event_data:
    event_type: modified
action:
  - service: local_file_update_file_path
    data_template:
      entity_id: camera.local_file_camera_01
      file_path: /config/www/media/cameras/ffmpeg_camera_01.jpg
  - service: local_file_update_file_path
    data_template:
      entity_id: camera.local_file_camera_01_doods
      file_path: /config/www/media/doods/doods_local_file_ffmpeg_camera_01.jpg
  - service: local_file_update_file_path
    data_template:
      entity_id: camera.local_file_amcrest_camera_01
      file_path: /config/www/media/cameras/amcrest_camera_01.jpg
  - service: local_file_update_file_path
    data_template:
      entity_id: camera.local_file_amcrest_camera_01_doods
      file_path: /config/www/media/doods/doods_local_file_amcrest_camera_01.jpg
