alias: 'Telegram Bacab Home Bot Frontyard'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/frontyard'
action:
  - service: script.turn_on
    entity_id: script.ffmpeg_camera_01
