alias: 'Telegram Bacab Home Bot Alarm'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/alarm'
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm_control_panel_manual
  - service: media_player.volume_set
    entity_id: media_player.amigo
    data:
      volume_level: 1.0
  - service: script.turn_on
    entity_id: script.alarm_control_panel_manual_triggered
  - delay: '00:00:30'
  - service: media_player.turn_off
    entity_id: media_player.amigo
