alias: 'Telegram Bacab Home Bot Last Person'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/lastperson'
action:
  - service: script.turn_on
    entity_id: script.last_person
