alias: 'Telegram Bacab Home Bot Amcrest'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/amcrest'
action:
  - service: script.turn_on
    entity_id: script.amcrest
