alias: 'Telegram Bacab Home Bot Deepstack Latest Dog'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/dsldog'
action:
  - service: script.turn_on
    entity_id: script.deepstack_object_01_latest_dog
