alias: 'Telegram Bacab Home Bot Start'
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/start'
action:
  - service: notify.telegram_bacab_home_bot
    data:
      message: 'commands'
      data:
        keyboard:
          - '/ping, /status'
          - '/weather, /speak'
          - '/notify, /alarm'
          - '/ffmpeg, /amcrest'
          - '/lastperson'
