alias: 'Telegram Bacab Home Bot Notify'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/notify'
action:
  - service: script.turn_on
    entity_id: script.ffmpeg_camera_01_notify
  - service: script.turn_on
    entity_id: script.amcrest_camera_01_notify
