alias: 'Telegram Bacab Home Bot Ffmepg'
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/ffmpeg'
action:
  - service: script.turn_on
    entity_id: script.ffmpeg_camera_01_capture
  - service: script.turn_on
    entity_id: script.ffmpeg_camera_01_notify
