alias: 'Telegram Bacab Home Bot Start'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/start'
action:
  - service: notify.telegram_bacab_home_bot
    data:
      message: 'commands'
      data:
        keyboard:
          - '/ping, /weather'
          - '/speak, /frontyard'
          - '/alarm'
