platform: rest
resource: !secret applications_openvino_shopper_mood_monitor_cpp
name: Applications OpenVINO Shopper Mood Monitor CPP
body_on: '{"state": "start"}'
body_off: '{"state": "stop"}'
is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
