platform: rest
resource: !secret applications_openvino_restricted_zone_notifier_cpp
name: Applications OpenVINO Restricted Zone Notifier CPP
body_on: '{"state": "start"}'
body_off: '{"state": "stop"}'
is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
