alias: Night Xiaomi Door/Window Sensor One On Off
initial_state: 'true'
trigger:
  - platform: state
    entity_id: binary_sensor.xiaomi_door_window_sensor_one_contact
    to: 'on'
action:
  - service: light.turn_on
    entity_id: light.luz_cochera
  - delay:
      seconds: 30
  - service: light.turn_off
    entity_id: light.luz_cochera
