alias: Night Hue Motion Sensor 01 Off
initial_state: 'false'
trigger:
  platform: state
  entity_id: binary_sensor.hue_motion_sensor_01_motion
  to: 'off'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.mobile_room_light
      state: 'on'
    - condition: or
      conditions:
        - condition: sun
          before: sunrise
        - condition: sun
          after: sunset
action:
  service: light.turn_off
  entity_id: light.mobile_room_light
