alias: Alarm Control Panel Manual Arm Night
initial_state: 'true'
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm_control_panel_manual
    to: 'armed_night'
action:
  - service: notify.telegram_bacab_home_bot
    data_template:
      message: "Alarm! Armed Night {{ states('sensor.date_time') }}"
