alias: Dark Sky Precipitation Intensity
trigger:
  - platform: state
    entity_id: sensor.dark_sky_precip
    to: 'rain'
  - platform: state
    entity_id: sensor.dark_sky_precip_0d
    to: 'rain'
  - platform: numeric_state
    entity_id: sensor.dark_sky_precip_probability_0d
    above: '50'
condition:
  - condition: state
    entity_id: sun.sun
    state: 'above_horizon'
action:
  - service: script.turn_on
    data_template:
    entity_id: >-
      {% if is_state('binary_sensor.rain', 'on') %}
         script.rain_light_notification
      {% endif %}
