alias: Family Mode Vacation Off
trigger:
  - platform: state
    entity_id: person.balam
    from: 'away'
    to: 'home'
action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.family_mode_vacation
