alias: FFmpeg Camera 01 Cast Play Off
initial_state: 'true'
trigger:
- platform: state
  entity_id: binary_sensor.ffmpeg_camera_01_cast
  from: 'on'
  to: 'off'
action:
  - service: media_player.turn_off
    entity_id: media_player.eek
