alias: Hue Outdoor Motion Sensor 01 On
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.hue_outdoor_motion_sensor_01_motion
  to: 'on'
action:
  - service: camera.snapshot
    data:
      entity_id: camera.mjpeg_camera_01
      filename: '/config/www/media/frontyard/{{ entity_id }}_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
  - service: camera.record
    data:
      entity_id: camera.mjpeg_camera_01
      filename: '/config/www/media/frontyard/{{ entity_id }}_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
