alias: Hue Outdoor Motion Sensor 01 On Doods
trigger:
  - platform: state
    entity_id: binary_sensor.hue_outdoor_motion_sensor_01_motion
    to: 'on'
action:
  - service: image_processing.scan
    data:
      entity_id: camera.ffmpeg_camera_01
