alias: Mode Vacation Off
trigger:
  - platform: state
    entity_id: person.balam
    from: 'not_home'
    to: 'home'
action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.mode_vacation
