alias: Night Hue Motion Sensor 02 On
initial_state: 'true'
trigger:
  platform: state
  entity_id: binary_sensor.hue_motion_sensor_02_motion
  to: 'on'
condition:
  condition: state
  entity_id: light.hallway_light
  state: 'off'
action:
  service: light.turn_on
  entity_id: light.hallway_light
