alias: Night Hue Motion Sensor 02 Off
initial_state: 'true'
trigger:
  platform: state
  entity_id: binary_sensor.hue_motion_sensor_02_motion
  to: 'off'
condition:
  condition: state
  entity_id: light.hallway_light
  state: 'on'
action:
  service: light.turn_off
  entity_id: light.hallway_light
