alias: alwaysAI Simple Object Counter Bicycle
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.alwaysai_simple_object_counter_bicycle
  from: 'off'
  to: 'on'
action:
  - service: camera.record
    data_template:
      entity_id: camera.camara_exterior
      filename: '/config/www/media/applications/alwaysai/bicycle/{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 30
      lookback: 20
