alias: alwaysAI People Counter
initial_state: true
mode: queued
trigger:
  platform: state
  entity_id: binary_sensor.alwaysai_people_counter
  from: 'off'
  to: 'on'
  for:
    seconds: 1
action:
  - service: camera.snapshot
    data:
      entity_id: camera.camara_exterior
      filename: '/config/www/media/applications/alwaysai_people_counter.jpg'
  - service: camera.record
    data_template:
      entity_id: camera.camara_exterior
      filename: '/config/www/media/applications/alwaysai/person/{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 30
      lookback: 20
  - service: camera.snapshot
    data:
      entity_id: camera.alwaysai_object_detector_and_classifier_face
      filename: '/config/www/media/applications/alwaysai/person/{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
  - service: notify.telegram_bacab_home_bot
    data:
      title: 'alwaysAI People Counter'
      message: "People"
      data:
        photo:
          - file: '/config/www/media/applications/alwaysai_people_counter.jpg'
            caption: People
