alias: Xiaomi Door Window Sensor One Contact On Telegram
initial_state: true
mode: queued
trigger:
  - platform: state
    entity_id: binary_sensor.xiaomi_door_window_sensor_one_contact
    to: 'on'
condition:
  condition: time
  after: '22:00:00'
  before: '08:00:00'
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
action:
  - service: notify.telegram_bacab_home_bot
    data:
      title: 'Xiaomi Door/Window Sensor'
      message: "First Contact"
