alias: Updater
trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
action:
  - service: persistent_notification.create
    data_template:
      message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
      title: "Home Assistant New Version"
