# https://www.home-assistant.io/components/sensor.mqtt/

platform: mqtt
name: Applications OpenVINO Shopper Gaze Monitor CPP Lookers
state_topic: "retail/traffic"
value_template: "{{ value_json.Lookers }}"
unit_of_measurement: 'Count'
