# https://www.home-assistant.io/components/sensor.mqtt/

platform: mqtt
name: Applications OpenVINO Shopper Mood Monitor CPP Anger
state_topic: "retail/traffic"
value_template: "{{ value_json.anger }}"
unit_of_measurement: 'Count'
