# https://www.home-assistant.io/components/sensor.mqtt/

platform: mqtt
name: Applications OpenVINO Shopper Mood Monitor CPP Happy
state_topic: "retail/traffic"
value_template: "{{ value_json.happy }}"
unit_of_measurement: 'Count'
