# https://www.home-assistant.io/integrations/template/

platform: template
sensors:
  template_total_automations:
    friendly_name: Template Total Automations
    value_template: >
      {%- set domains = ['automation'] -%}
      {%- for domain in domains -%}
        {%- for item in states[domain] -%}
         {% if loop.first %}
           {{loop.length}}
         {% endif %}
        {%- endfor -%}
      {%- endfor -%}
