alias: Family Mode Emergency Off
initial_state: 'true'
trigger:
  - platform: state
    entity_id: input_boolean.family_mode_emergency
    from: 'on'
    to: 'off'
action:
  - service: script.turn_on
    entity_id: script.family_mode_emergency_off
