alias: 'Family Mode Vacation On'
trigger:
  - platform: state
    entity_id: person.balam
    from: 'home'
    to: 'not_home'
    for:
      hours: 18
      minutes: 0
      seconds: 0
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.family_mode_vacation
